force-app/main/default/objects/uNI_Logframe__c/uNI_Logframe__c.object-meta.xml
<CustomObject>
    <label>Logframe</label>
    <nameField>
        <label>Logframe Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logframes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/uNI_Logframe__c/fields/uNI_Individual_Application__c.field-meta.xml
<CustomField>
    <fullName>uNI_Individual_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Individual Application</label>
    <referenceTo>IndividualApplication</referenceTo>
    <relationshipLabel>Logframes</relationshipLabel>
    <relationshipName>Logframes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/uNI_Logframe__c/fields/uNI_LogframeVersion__c.field-meta.xml
<CustomField>
    <fullName>uNI_LogframeVersion__c</fullName>
    <description>Version of the logframe</description>
    <label>Logframe Version</label>
    <length>155</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/uNI_Milestone__c/uNI_Milestone__c.object-meta.xml
<CustomObject>
    <label>Milestone</label>
    <nameField>
        <displayFormat>MI-{0000}</displayFormat>
        <label>Milestone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/uNI_Milestone__c/fields/uNI_BehindSchedule__c.field-meta.xml
<CustomField>
    <fullName>uNI_BehindSchedule__c</fullName>
    <formula>AND(
    TODAY() &gt; uNI_Milestone_Date__c,
    ISPICKVAL(uNI_Status__c, &quot;Completed&quot;) = FALSE
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Behind Schedule</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/uNI_Milestone__c/fields/uNI_Comments__c.field-meta.xml
<CustomField>
    <fullName>uNI_Comments__c</fullName>
    <label>Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/uNI_Milestone__c/fields/uNI_Comments_from_Implementer_Year1__c.field-meta.xml
<CustomField>
    <fullName>uNI_Comments_from_Implementer_Year1__c</fullName>
    <label>Comments from Implementer</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/uNI_Milestone__c/fields/uNI_Comments_from_Implementer_Year2__c.field-meta.xml
<CustomField>
    <fullName>uNI_Comments_from_Implementer_Year2__c</fullName>
    <label>Comments from Implementer</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/uNI_Milestone__c/fields/uNI_Comments_from_Implementer_Year3__c.field-meta.xml
<CustomField>
    <fullName>uNI_Comments_from_Implementer_Year3__c</fullName>
    <label>Comments from Implementer</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/uNI_Milestone__c/fields/uNI_CompletionDate__c.field-meta.xml
<CustomField>
    <fullName>uNI_CompletionDate__c</fullName>
    <label>Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/uNI_Milestone__c/fields/uNI_Description__c.field-meta.xml
<CustomField>
    <fullName>uNI_Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/uNI_Milestone__c/fields/uNI_LogframeVersion__c.field-meta.xml
<CustomField>
    <fullName>uNI_LogframeVersion__c</fullName>
    <description>value of LogframeVersion same as value of LogframeVersion in logframe object to handle the versioning</description>
    <label>Logframe Version</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/uNI_Milestone__c/fields/uNI_Milestone_Date__c.field-meta.xml
<CustomField>
    <fullName>uNI_Milestone_Date__c</fullName>
    <label>Milestone Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/uNI_Milestone__c/fields/uNI_Milestone_Heading__c.field-meta.xml
<CustomField>
    <fullName>uNI_Milestone_Heading__c</fullName>
    <label>Milestone Heading</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/uNI_Milestone__c/fields/uNI_Milestone_Title__c.field-meta.xml
<CustomField>
    <fullName>uNI_Milestone_Title__c</fullName>
    <label>Milestone Title</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/uNI_Milestone__c/fields/uNI_Outcome__c.field-meta.xml
<CustomField>
    <fullName>uNI_Outcome__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outcome</label>
    <referenceTo>uNI_PortfolioOutcomes__c</referenceTo>
    <relationshipLabel>Milestones</relationshipLabel>
    <relationshipName>Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/uNI_Milestone__c/fields/uNI_Output__c.field-meta.xml
<CustomField>
    <fullName>uNI_Output__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Output</label>
    <referenceTo>uNI_PortfolioOutput__c</referenceTo>
    <relationshipLabel>Milestones</relationshipLabel>
    <relationshipName>Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/uNI_Milestone__c/fields/uNI_Revised_Due_Date_Year1__c.field-meta.xml
<CustomField>
    <fullName>uNI_Revised_Due_Date_Year1__c</fullName>
    <label>Revised Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/uNI_Milestone__c/fields/uNI_Revised_Due_Date_Year2__c.field-meta.xml
<CustomField>
    <fullName>uNI_Revised_Due_Date_Year2__c</fullName>
    <label>Revised Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/uNI_Milestone__c/fields/uNI_Revised_Due_Date_Year3__c.field-meta.xml
<CustomField>
    <fullName>uNI_Revised_Due_Date_Year3__c</fullName>
    <label>Revised Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/uNI_Milestone__c/fields/uNI_Status__c.field-meta.xml
<CustomField>
    <fullName>uNI_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Significant progress</fullName>
            </value>
            <value>
                <fullName>Limited progress</fullName>
            </value>
            <value>
                <fullName>Not started</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/uNI_Outcome__c/uNI_Outcome__c.object-meta.xml
<CustomObject>
    <label>Outcome</label>
    <nameField>
        <displayFormat>oc-{000000}</displayFormat>
        <label>Outcome Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outcomes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/uNI_Outcome__c/fields/uNI_Description__c.field-meta.xml
<CustomField>
    <fullName>uNI_Description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/uNI_Outcome__c/fields/uNI_Logframe__c.field-meta.xml
<CustomField>
    <fullName>uNI_Logframe__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Logframe</label>
    <referenceTo>uNI_Logframe__c</referenceTo>
    <relationshipLabel>Outcomes</relationshipLabel>
    <relationshipName>Outcomes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/uNI_Output__c/uNI_Output__c.object-meta.xml
<CustomObject>
    <label>Output</label>
    <nameField>
        <displayFormat>op-{000000}</displayFormat>
        <label>Output Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outputs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/uNI_Output__c/fields/uNI_Logframe__c.field-meta.xml
<CustomField>
    <fullName>uNI_Logframe__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Logframe</label>
    <referenceTo>uNI_Logframe__c</referenceTo>
    <relationshipLabel>Outputs</relationshipLabel>
    <relationshipName>Outputs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/uNI_PortfolioOutcomes__c/uNI_PortfolioOutcomes__c.object-meta.xml
<CustomObject>
    <label>Portfolio Outcome</label>
    <nameField>
        <displayFormat>O/C-{0000}</displayFormat>
        <label>Portfolio Outcomes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portfolio Outcomes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/uNI_PortfolioOutcomes__c/fields/uNI_Logframe__c.field-meta.xml
<CustomField>
    <fullName>uNI_Logframe__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Logframe</label>
    <referenceTo>uNI_Logframe__c</referenceTo>
    <relationshipLabel>Portfolio Outcomes</relationshipLabel>
    <relationshipName>Portfolio_Outcomes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/uNI_PortfolioOutcomes__c/fields/uNI_LogframeVersion__c.field-meta.xml
<CustomField>
    <fullName>uNI_LogframeVersion__c</fullName>
    <description>value LogframeVersion same as value LogframeVersion in logframe to handle the versioning</description>
    <label>Logframe Version</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/uNI_PortfolioOutcomes__c/fields/uNI_Outcome__c.field-meta.xml
<CustomField>
    <fullName>uNI_Outcome__c</fullName>
    <label>Outcome</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/uNI_PortfolioOutput__c/uNI_PortfolioOutput__c.object-meta.xml
<CustomObject>
    <label>Portfolio Output</label>
    <nameField>
        <displayFormat>O/p-{0000}</displayFormat>
        <label>Protfolio Output Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portfolio Outputs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/uNI_PortfolioOutput__c/fields/uNI_Logframe__c.field-meta.xml
<CustomField>
    <fullName>uNI_Logframe__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Logframe</label>
    <referenceTo>uNI_Logframe__c</referenceTo>
    <relationshipLabel>Portfolio Outputs</relationshipLabel>
    <relationshipName>Portfolio_Outputs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/uNI_PortfolioOutput__c/fields/uNI_LogframeVersion__c.field-meta.xml
<CustomField>
    <fullName>uNI_LogframeVersion__c</fullName>
    <description>value of LogframeVersion same as LogframeVersion in logframe obj</description>
    <label>Logframe Version</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/uNI_PortfolioOutput__c/fields/uNI_OutputTitle__c.field-meta.xml
<CustomField>
    <fullName>uNI_OutputTitle__c</fullName>
    <label>Output Title</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/uNI_CloneMilestone.cls
/**
* @File Name : uNI_CloneMilestone.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : November 21, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | November 21, 2025 |   | Initial Version
**/

// Invocable clone helper used by Create/Return Reprogramming flows.
public without sharing class uNI_CloneMilestone {

    public class Request {
        @InvocableVariable(required=true)
        public Id individualApplicationId;

        @InvocableVariable(required=true)
        public String sourceVersion;

        @InvocableVariable(required=true)
        public String targetVersion;

        @InvocableVariable
        public Id logframeId;
    }

    public class Response {
        @InvocableVariable public Id individualApplicationId;
        @InvocableVariable public String sourceVersion;
        @InvocableVariable public String targetVersion;
        @InvocableVariable public Integer recordsCloned;
        @InvocableVariable public List<String> errors;
    }

    @InvocableMethod(label='Clone Milestones (previous → target version)')
    public static List<Response> run(List<Request> requests) {
        List<Response> results = new List<Response>();
        if (requests == null) {
            return results;
        }
        for (Request req : requests) {
            results.add(cloneMilestones(req));
        }
        return results;
    }

    private static Response cloneMilestones(Request req) {
        Response res = new Response();
        res.errors = new List<String>();

        if (req == null ||
            req.individualApplicationId == null ||
            String.isBlank(req.sourceVersion) ||
            String.isBlank(req.targetVersion)) {
            res.errors.add('Missing individualApplicationId, sourceVersion, or targetVersion.');
            return res;
        }

        res.individualApplicationId = req.individualApplicationId;
        res.sourceVersion = req.sourceVersion;
        res.targetVersion = req.targetVersion;

        Id iaId = req.individualApplicationId;

        uNI_Logframe__c sourceLogframe = resolveLogframe(iaId, req.sourceVersion);
        if (sourceLogframe == null) {
            res.errors.add('No logframe found for source version ' + req.sourceVersion);
            return res;
        }

        uNI_Logframe__c targetLogframe = resolveLogframe(iaId, req.targetVersion);
        if (targetLogframe == null) {
            if (req.logframeId != null) {
                targetLogframe = new uNI_Logframe__c(Id = req.logframeId, uNI_LogframeVersion__c = req.targetVersion);
            } else {
                res.errors.add('No logframe found for target version ' + req.targetVersion);
                return res;
            }
        }

        Map<Id, String> sourceOutputMap = new Map<Id, String>();
        for (uNI_PortfolioOutput__c output : [
            SELECT Id, uNI_OutputTitle__c
            FROM uNI_PortfolioOutput__c
            WHERE uNI_Logframe__c = :sourceLogframe.Id
        ]) {
            sourceOutputMap.put(output.Id, output.uNI_OutputTitle__c);
        }
        Map<String, Id> targetOutputMap = new Map<String, Id>();
        for (uNI_PortfolioOutput__c output : [
            SELECT Id, uNI_OutputTitle__c
            FROM uNI_PortfolioOutput__c
            WHERE uNI_Logframe__c = :targetLogframe.Id
        ]) {
            targetOutputMap.put(output.uNI_OutputTitle__c, output.Id);
        }

        Map<Id, String> sourceOutcomeMap = new Map<Id, String>();
        for (uNI_PortfolioOutcomes__c outcome : [
            SELECT Id, Name
            FROM uNI_PortfolioOutcomes__c
            WHERE uNI_Logframe__c = :sourceLogframe.Id
        ]) {
            sourceOutcomeMap.put(outcome.Id, outcome.Name);
        }
        Map<String, Id> targetOutcomeMap = new Map<String, Id>();
        for (uNI_PortfolioOutcomes__c outcome : [
            SELECT Id, Name
            FROM uNI_PortfolioOutcomes__c
            WHERE uNI_Logframe__c = :targetLogframe.Id
        ]) {
            targetOutcomeMap.put(outcome.Name, outcome.Id);
        }

        Set<Id> sourceOutputIds = new Set<Id>(sourceOutputMap.keySet());
        Set<Id> sourceOutcomeIds = new Set<Id>(sourceOutcomeMap.keySet());

        if (sourceOutputIds.isEmpty() && sourceOutcomeIds.isEmpty()) {
            res.errors.add('Source logframe has no outputs or outcomes to clone.');
            return res;
        }

        List<uNI_Milestone__c> sourceMilestones = [
            SELECT Id,
                   Name,
                   uNI_Revised_Due_Date_Year1__c,
                   uNI_Comments_from_Implementer_Year1__c,
                   uNI_Milestone_Heading__c,
                   uNI_Comments__c,
                   uNI_Outcome__c,
                   uNI_Output__c,
                   uNI_Milestone_Date__c,
                   uNI_Status__c,
                   uNI_Revised_Due_Date_Year2__c,
                   uNI_Revised_Due_Date_Year3__c,
                   uNI_Comments_from_Implementer_Year2__c,
                   uNI_Comments_from_Implementer_Year3__c,
                   uNI_LogframeVersion__c,
                   uNI_CompletionDate__c,
                   uNI_BehindSchedule__c,
                   uNI_Description__c,
                   uNI_Milestone_Title__c
            FROM uNI_Milestone__c
            WHERE (uNI_Output__c IN :sourceOutputIds OR uNI_Outcome__c IN :sourceOutcomeIds)
        ];

        if (sourceMilestones.isEmpty()) {
            res.recordsCloned = 0;
            return res;
        }

        List<uNI_Milestone__c> clones = new List<uNI_Milestone__c>();
        for (uNI_Milestone__c sourceMilestone : sourceMilestones) {
            uNI_Milestone__c clone = sourceMilestone.clone(false, false, false);
            clone.uNI_LogframeVersion__c = req.targetVersion;

            Id targetOutputId = rebindByLabel(
                sourceMilestone.uNI_Output__c,
                sourceOutputMap,
                targetOutputMap
            );
            clone.uNI_Output__c = targetOutputId;

            Id targetOutcomeId = rebindByLabel(
                sourceMilestone.uNI_Outcome__c,
                sourceOutcomeMap,
                targetOutcomeMap
            );
            clone.uNI_Outcome__c = targetOutcomeId;
            clones.add(clone);
        }

        Database.SaveResult[] saveResults = Database.insert(clones, false);
        Integer successCount = 0;
        for (Integer i = 0; i < saveResults.size(); i++) {
            if (saveResults[i].isSuccess()) {
                successCount++;
            } else if (saveResults[i].getErrors() != null && !saveResults[i].getErrors().isEmpty()) {
                res.errors.add(
                    'Clone failed for milestone ' + sourceMilestones[i].Id + ': ' +
                    saveResults[i].getErrors()[0].getMessage()
                );
            }
        }
        res.recordsCloned = successCount;
        return res;
    }

    private static uNI_Logframe__c resolveLogframe(Id iaId, String version) {
        List<uNI_Logframe__c> logframes = [
            SELECT Id, uNI_LogframeVersion__c
            FROM uNI_Logframe__c
            WHERE uNI_Individual_Application__c = :iaId
              AND uNI_LogframeVersion__c = :version
            ORDER BY CreatedDate DESC
            LIMIT 1
        ];
        return logframes.isEmpty() ? null : logframes[0];
    }

    private static Id rebindByLabel(
        Id sourceId,
        Map<Id, String> sourceMap,
        Map<String, Id> targetMap
    ) {
        if (sourceId == null) {
            return null;
        }
        String label = sourceMap.get(sourceId);
        if (label == null) {
            return null;
        }
        return targetMap.get(label);
    }
}