force-app/main/default/objects/uNI_Reviewer__c/uNI_Reviewer__c.object-meta.xml
<CustomObject>
    <description>Reviewers which will take part in the Proposal Selection process on the Call For Proposals(Funding Oppty) and Submitted Proposals (Individual Application) obj. This object will also contain project team members for processess like GAD PPF, The lead implementers and contributors can also be present here,</description>
    <label>Reviewer</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Reviewer Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviewers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/uNI_Reviewer__c/fields/uNI_IndividualApplication__c.field-meta.xml
<CustomField>
    <fullName>uNI_IndividualApplication__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Individual Application</label>
    <referenceTo>IndividualApplication</referenceTo>
    <relationshipLabel>Reviewers</relationshipLabel>
    <relationshipName>uNI_ApplicationReviewers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/uNI_Reviewer__c/fields/uNI_ReviewerRole__c.field-meta.xml
<CustomField>
    <fullName>uNI_ReviewerRole__c</fullName>
    <label>Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Level 1</fullName>
            </value>
            <value>
                <fullName>Level 2</fullName>
            </value>
            <value>
                <fullName>Level 3</fullName>
            </value>
            <value>
                <fullName>PRC</fullName>
            </value>
            <value>
                <fullName>JRC</fullName>
            </value>
            <value>
                <fullName>PM</fullName>
            </value>
            <value>
                <fullName>PO</fullName>
            </value>
            <value>
                <fullName>Strategy</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Director FA</fullName>
            </value>
            <value>
                <fullName>Director PD</fullName>
            </value>
            <value>
                <fullName>PD TL</fullName>
            </value>
            <value>
                <fullName>ED</fullName>
            </value>
            <value>
                <fullName>Grant Finance</fullName>
            </value>
            <value>
                <fullName>MEL</fullName>
            </value>
            <value>
                <fullName>Procurement</fullName>
            </value>
            <value>
                <fullName>Implementer</fullName>
            </value>
            <value>
                <fullName>Contributor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/uNI_Reviewer__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Proposal_Reviewers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/uNI_ProjectTeamController.cls
public with sharing class uNI_ProjectTeamController {
    public class ProjectTeamRow {
        @AuraEnabled public String role;
        @AuraEnabled public String userName;
        public ProjectTeamRow(String role, String userName) {
            this.role = role;
            this.userName = userName;
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<ProjectTeamRow> getProjectTeam(Id investmentId) {
        if (investmentId == null) {
            System.debug(LoggingLevel.WARN, 'uNI_ProjectTeamController.getProjectTeam: investmentId is null');
            return new List<ProjectTeamRow>();
        }
        System.debug(LoggingLevel.INFO, 'uNI_ProjectTeamController.getProjectTeam: investmentId=' + investmentId);
        System.debug(LoggingLevel.INFO, 'uNI_ProjectTeamController.getProjectTeam: userId=' + UserInfo.getUserId() +
            ', profileId=' + UserInfo.getProfileId() + ', userType=' + UserInfo.getUserType());
        List<String> roles = new List<String>{ 'PM', 'PO', 'Strategy', 'Legal', 'MEL', 'Procurement' };
        String roleFilter = '\'' + String.join(roles, '\',\'') + '\'';
        List<ProjectTeamRow> rows = new List<ProjectTeamRow>();
        String soql =
            'SELECT uNI_ReviewerRole__c, User__r.Name, User__r.FirstName, User__r.LastName, User__r.Alias ' +
            'FROM uNI_Reviewer__c ' +
            'WHERE uNI_IndividualApplication__c = :investmentId ' +
            'AND uNI_ReviewerRole__c INCLUDES (' + roleFilter + ') ' +
            'ORDER BY CreatedDate ASC';

        for (uNI_Reviewer__c rec : Database.query(soql)) {
            rows.add(new ProjectTeamRow(rec.uNI_ReviewerRole__c, buildUserDisplayName(rec)));
        }
        return rows;
    }

    @AuraEnabled(cacheable=true)
    public static List<ProjectTeamRow> getImplementingPartners(Id investmentId) {
        if (investmentId == null) {
            System.debug(LoggingLevel.WARN, 'uNI_ProjectTeamController.getImplementingPartners: investmentId is null');
            return new List<ProjectTeamRow>();
        }
        List<String> roles = new List<String>{ 'Implementer', 'Contributor' };
        String roleFilter = '\'' + String.join(roles, '\',\'') + '\'';
        List<ProjectTeamRow> rows = new List<ProjectTeamRow>();
        String soql =
            'SELECT uNI_ReviewerRole__c, User__r.Name, User__r.FirstName, User__r.LastName, User__r.Alias ' +
            'FROM uNI_Reviewer__c ' +
            'WHERE uNI_IndividualApplication__c = :investmentId ' +
            'AND uNI_ReviewerRole__c INCLUDES (' + roleFilter + ') ' +
            'ORDER BY CreatedDate ASC';

        for (uNI_Reviewer__c rec : Database.query(soql)) {
            rows.add(new ProjectTeamRow(rec.uNI_ReviewerRole__c, buildUserDisplayName(rec)));
        }
        return rows;
    }
    
    private static String buildUserDisplayName(uNI_Reviewer__c rec) {
        String displayName = '';
        if (rec.User__r != null) {
            String firstName = rec.User__r.FirstName;
            String lastName = rec.User__r.LastName;
            if (!String.isBlank(firstName) || !String.isBlank(lastName)) {
                displayName = String.join(new List<String>{ firstName, lastName }, ' ').trim();
            } else if (!String.isBlank(rec.User__r.Name) && !rec.User__r.Name.startsWith('User')) {
                displayName = rec.User__r.Name;
            } else if (!String.isBlank(rec.User__r.Alias)) {
                displayName = rec.User__r.Alias;
            }
        }
        return displayName;
    }
}